/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2017-09-26 05:30:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.notice;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import notice.model.vo.Notice;
import member.model.vo.Member;

public final class noticeDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/notice/../../header.jsp", Long.valueOf(1506391320719L));
    _jspx_dependants.put("/views/notice/../../footer.html", Long.valueOf(1506389128283L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("notice.model.vo.Notice");
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Notice notice = (Notice)request.getAttribute("notice");

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>noticeDetailView</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

	Member member = (Member)session.getAttribute("member");

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>first</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tul { list-style: none; }\r\n");
      out.write("\tnav ul li {\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tnav ul li a {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\twidth: 150px;\r\n");
      out.write("\t\theight: 35px;\r\n");
      out.write("\t\tbackground: orange;\r\n");
      out.write("\t\tcolor: navy;\r\n");
      out.write("\t\tpadding-top: 7px;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\ttext-shadow: 1px 1px 4px black;\r\n");
      out.write("\t\tmargin-right: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tnav ul li a:hover{ background: olive; }\r\n");
      out.write("\t\r\n");
      out.write("\tdiv#loginBox {\r\n");
      out.write("\t\tbackground : lightgray;\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\tborder: 1px dotted gray;\r\n");
      out.write("\t\tmargin-right: 200px;\r\n");
      out.write("\t\tfont-size: 9pt;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("<h1>Welcome firstWebProject</h1>\r\n");
      out.write("<nav>\r\n");
      out.write("<ul>\r\n");
      out.write("\t<li><a href=\"#\">메뉴1</a></li>\r\n");
      out.write("\t<li><a href=\"/first/nlist\">공지사항</a></li>\r\n");
      out.write("\t<li><a href=\"#\">메뉴3</a></li>\r\n");
      out.write("\t<li><a href=\"#\">메뉴4</a></li>\r\n");
      out.write("\t<li><a href=\"#\">메뉴5</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("</header>\r\n");
      out.write("<hr style=\"clear:left;\">\r\n");
      out.write("<div id=\"loginBox\">\r\n");
      out.write('\r');
      out.write('\n');
  if(member == null){ 
      out.write("\r\n");
      out.write("<form action=\"login\" method=\"post\">\r\n");
      out.write("<input type=\"text\" name=\"userid\" placeholder=\"아이디 입력\"> <br>\r\n");
      out.write("<input type=\"password\" name=\"userpwd\" placeholder=\"암호 입력\"> <br>\r\n");
      out.write("<input type=\"submit\" value=\"로그인\">\r\n");
      out.write("</form>\r\n");
      out.write("<a href=\"views/member/enrollForm.html\">회원가입</a> &nbsp;\r\n");
      out.write("<a>아이디/비밀번호 조회</a>\r\n");
  }else{ 
      out.write('\r');
      out.write('\n');
      out.print( member.getMemberName() );
      out.write(" 님 &nbsp; \r\n");
      out.write("<a href=\"logout\">로그아웃</a> <br>\r\n");
      out.write("<!-- <a href=\"views/member/myInfo.jsp\">내정보보기</a> -->\r\n");
      out.write("\r\n");
      out.write("<a href=\"minfo?userid=");
      out.print( member.getMemberId() );
      out.write("\">내정보보기</a>\r\n");
  } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<session>\r\n");
      out.write("\t\t<h2 align=\"center\">");
      out.print( notice.getNoticeNo() );
      out.write("번 공지글 상세보기</h2><br>\r\n");
      out.write("<table border=\"1\" cellspacing=\"0\" width=\"600\" align=\"center\">\r\n");
      out.write("\t<tr><th>제목</th><td>");
      out.print( notice.getNoticeTitle() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr><th>작성자</th><td>");
      out.print( notice.getNoticeWriter() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr><th>작성날짜</th><td>");
      out.print( notice.getNoticeDate() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr><th>첨부파일</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t");
 if(notice.getOriginalFileName() != null){ 
      out.write("\r\n");
      out.write("\t\t\t<a href=\"/first/fdown?oname=");
      out.print( notice.getOriginalFileName() );
      out.write("&rname=");
      out.print( notice.getRenameFileName() );
      out.write('"');
      out.write('>');
      out.print( notice.getOriginalFileName() );
      out.write("</a>\r\n");
      out.write("\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t첨부파일 없음\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><th>조회수</th><td>");
      out.print( notice.getReadCount() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr><th>내용</th><td>");
      out.print( notice.getNoticeContent() );
      out.write("</td></tr>\r\n");
      out.write("\t");
 if(notice.getNoticeWriter().equals(member.getMemberId())){ 
      out.write("\r\n");
      out.write("\t<tr><th colspan=\"2\">\r\n");
      out.write("\t\t<a href=\"/first/nupview?no=");
      out.print( notice.getNoticeNo() );
      out.write("\">수정페이지로 이동</a> &nbsp;\r\n");
      out.write("\t\t<a href=\"/first/ndel?no=");
      out.print( notice.getNoticeNo() );
      out.write("\">삭제하기</a>\r\n");
      out.write("\t</th></tr>\r\n");
      out.write("\t");
 } 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<br>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\t<a href=\"/first/nlist\">목록보기로 이동</a>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br>\r\n");
      out.write("<hr>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div align=\"center\" style=\"background:black; color:white; font-weight: bold;\">\r\n");
      out.write("\tcopyright@kh.org 2017.09.26 íê¸¸ë ì ì<br>\r\n");
      out.write("\tadmin@iei.or.kr  Tel : 02-1234-5678 fax: 02-1234-5677\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
