--1. 
CREATE TABLE TB_CATEGORY(
NAME VARCHAR(10),
USE_YN CHAR(1) DEFAULT 'Y'
);

--2.
CREATE TABLE TB_CLASS_TYPE(
NO VARCHAR2(5),
NAME VARCHAR2(10),
CONSTRAINT PNO PRIMARY KEY(NO)
);

--3.
ALTER TABLE TB_CATEGORY
ADD CONSTRAINT PNAME PRIMARY KEY(NAME);

--4.
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME NOT NULL;

--5.
ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR(10);
ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR2(20);

--6.
ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_TYPE_NO;
ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;

--7.
ALTER TABLE TB_CLASS_TYPE
RENAME CONSTRAINT PNO TO PK_CLASS_TYPE_NO;
ALTER TABLE TB_CATEGORY
RENAME CONSTRAINT PNAME TO PK_CATEGORY_NAME;

--8.
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT; 

--9.
ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);

--10.
CREATE VIEW VW_학생일반정보(학번, 학생이름, 주소)
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT;

--11.
CREATE VIEW VW_지도면담(학생이름, 학과이름, 지도교수이름)
AS SELECT STUDENT_NAME, DEPARTMENT_NAME, PROFESSOR_NAME
FROM TB_STUDENT
INNER JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT OUTER JOIN TB_PROFESSOR ON(TB_STUDENT.COACH_PROFESSOR_NO=TB_PROFESSOR.PROFESSOR_NO)
ORDER BY 2,1;

--12.
CREATE VIEW VW_학과별학생수(DEPARTMENT_NAME, STUDENT_COUNT)
AS SELECT DEPARTMENT_NAME, COUNT(*)
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING (DEPARTMENT_NO)
GROUP BY DEPARTMENT_NAME
ORDER BY 1;

--13.
UPDATE "VW_학생일반정보"
SET "학생이름" = '황효혁'
WHERE 학번 = 'A213046';

SELECT * FROM "VW_학생일반정보"
WHERE 학번 = 'A213046';

--14.
CREATE VIEW VW_학생일반정보(학번, 학생이름, 주소)
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WITH READ ONLY;--추가

--15.
SELECT *
FROM(
SELECT CLASS_NO 과목번호, CLASS_NAME 과목이름, COUNT(*) AS "누적수강생수(명)"
FROM TB_CLASS
INNER JOIN TB_GRADE USING(CLASS_NO)
WHERE TO_NUMBER(SUBSTR(TERM_NO,1,4)) >((
SELECT *
FROM (
SELECT TO_NUMBER(SUBSTR(TERM_NO,1,4))
FROM TB_GRADE
ORDER BY TO_NUMBER(SUBSTR(TERM_NO,1,4)) DESC)
WHERE ROWNUM=1)-5) -- 최근 5년
GROUP BY CLASS_NO,CLASS_NAME
ORDER BY 3 DESC
)
WHERE ROWNUM<4;

--DML
--1.
COMMIT;