DROP TABLE NOTICE CASCADE CONSTRAINTS;

CREATE TABLE NOTICE(
  NOTICE_NO   NUMBER,
  NOTICE_TITLE  VARCHAR2(50) NOT NULL,
  NOTICE_WRITER VARCHAR2(15) NOT NULL,
  NOTICE_CONTENT LONG,
  NOTICE_DATE DATE DEFAULT SYSDATE,
  ORIGINAL_FILENAME VARCHAR2(100),
  RENAME_FILENAME VARCHAR2(100),
  READ_COUNT  NUMBER DEFAULT 0,
  CONSTRAINT PK_NOTICENO PRIMARY KEY (NOTICE_NO),
  CONSTRAINT FK_NOTICEWR FOREIGN KEY (NOTICE_WRITER) REFERENCES MEMBER
);

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지글번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지글제목';
COMMENT ON COLUMN NOTICE.NOTICE_WRITER IS '공지글작성자아이디';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지글내용';
COMMENT ON COLUMN NOTICE.NOTICE_DATE IS '공지글올린날짜';
COMMENT ON COLUMN NOTICE.ORIGINAL_FILENAME IS '원래첨부파일명';
COMMENT ON COLUMN NOTICE.RENAME_FILENAME IS '바뀐첨부파일명';
COMMENT ON COLUMN NOTICE.READ_COUNT IS '조회수';

INSERT INTO NOTICE VALUES (1, '관리자 공지글1', 'admin', 
'웹 서비스가 개시되었습니다. 많이 이용해주세요.', DEFAULT, null, null, DEFAULT);

INSERT INTO NOTICE VALUES (2, '축하합니다.', 'user11', 
'많이 이용하겠습니다. 좋은 서비스 기대합니다.', DEFAULT, NULL, NULL, DEFAULT);

INSERT INTO NOTICE VALUES (3, '추카추카...', 'user22',
'방가방가...좋은 정보 제공해주세용..*^^*', DEFAULT, NULL, NULL, DEFAULT);


COMMIT;



