

SELECT EMP_NAME, DEPT_ID, JOB_ID, SALARY
FROM EMPLOYEE
WHERE SALARY BETWEEN 3500000 AND 5500000;

SELECT EMP_NAME, DEPT_ID, JOB_ID, SALARY
FROM EMPLOYEE;

--NULL인지 물을 때 컬럼명  IS NULL. 컬럼명 IS NOT NULL
--부서 배정도 받지 않고, 관리자 배정도 받지 않은 직원 조회

SELECT EMP_NAME, MGR_ID, DEPT_ID
FROM EMPLOYEE
WHERE MGR_ID IS NULL AND DEPT_ID IS NULL;

--부서와 직급을 배정받지않은 직원 조회

SELECT EMP_NAME, DEPT_ID, JOB_ID
FROM EMPLOYEE
WHERE DEPT_ID IS NULL AND JOB_ID IS NULL;

-- 60번 또는 90번 부서의 근무하는 직원의 이름, 부서코드, 급여 조회
SELECT EMP_NAME 이름, DEPT_ID 부서코드, SALARY 급여
FROM EMPLOYEE
--WHERE DEPT_ID = '60' OR DEPT_ID='90';
WHERE DEPT_ID IN ('60','90');
--IN 연산자 괄호안의 값들을 OR연산함

--60번,90번을 제외한 다른부서에 근무하는 직원 조회
SELECT EMP_NAME 이름, DEPT_ID 부서코드, SALARY 급여
FROM EMPLOYEE
--WHERE DEPT_ID = '60' OR DEPT_ID='90';
WHERE DEPT_ID NOT IN ('60','90');
--


--연산자 우선 순위 테스트
--부서코드가 20, 90이면서 3백만을 초과하는 급여를 받고 있는 직원 조회
SELECT EMP_NAME, DEPT_ID, SALARY
FROM EMPLOYEE
--WHERE (DEPT_ID ='20' OR DEPT_ID='90') AND SALARY > 3000000;
WHERE DEPT_ID IN('20','90') AND SALARY >3000000;

