 SET SERVEROUTPUT ON;
/
DECLARE
box NUMBER;
BEGIN
SELECT empno
INTO box
FROM emp
WHERE ename='WARD';
DBMS_OUTPUT.PUT_LINE(box);
EXCEPTION
WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('No Data!!!');
END;
/
DECLARE
N NUMBER := 1;
BEGIN
LOOP
DBMS_OUTPUT.PUT_LINE(N);
N := N + 1;
IF N > 5 THEN
EXIT;
END IF;
END LOOP;
END;
/
SHOW ERROR;
/

CREATE table test1(bunho number(3), irum varchar2(10));
/
BEGIN
FOR i IN 1..10 LOOP
insert into test1 values(i, SYSDATE);
END LOOP;
END;
/
DECLARE
 RESULT NUMBER;
BEGIN
 FOR DAN IN 2..9 LOOP
 IF MOD(DAN, 2) = 1 THEN
 FOR N IN 1..9 LOOP
 RESULT := DAN * N;
 DBMS_OUTPUT.PUT_LINE(DAN || ' * ' || N || ' = ' || RESULT);
 END LOOP;
 DBMS_OUTPUT.PUT_LINE(' ');
 END IF;
 END LOOP;
END;
/
DECLARE
N NUMBER := 2;
M NUMBER;
RESULT NUMBER;
BEGIN
WHILE N <= 9 LOOP
 IF MOD(N, 2) = 1 THEN
 M:=1;
WHILE M <= 9 LOOP
 RESULT := M * N;
 DBMS_OUTPUT.PUT_LINE(N || ' * ' || M || ' = ' || RESULT);
 M:= M+1;
END LOOP;
 DBMS_OUTPUT.PUT_LINE(' ');
 END IF;
N := N + 1;
END LOOP;
END;
/