--﻿JOIN 연습문제
--
--1. 2020년 12월 25일이 무슨 요일인지 조회하시오
SELECT TO_CHAR(TO_DATE('20201225','YYYYMMDD'),'DAY')AS "무슨요일?" FROM DUAL;
--
--
--2. 주민번호가 60년대 생이면서 성별이 여자이고, 성이 김씨인 직원들의 
--사원명, 주민번호, 부서명, 직급명을 조회하시오.
SELECT EMP_NAME, EMP_NO,DEPT_NAME,JOB_TITLE
FROM EMPLOYEE
JOIN JOB USING(JOB_ID)
JOIN DEPARTMENT USING(DEPT_ID)
WHERE EMP_NO LIKE '6%' AND EMP_NO LIKE '%-2%' AND EMP_NAME LIKE '김%';
--
--
--3. 가장 나이가 적은 직원의 사번, 사원명, 나이, 부서명, 직급명을 조회하시오.
SELECT *
FROM(
SELECT EMP_ID, EMP_NAME, TRUNC(MONTHS_BETWEEN(SYSDATE,TO_DATE(SUBSTR(EMP_NO,1,6),'RRMMDD'))/12)+1 AS 나이, DEPT_NAME,JOB_TITLE
FROM EMPLOYEE
JOIN JOB USING(JOB_ID)
JOIN DEPARTMENT USING(DEPT_ID)
ORDER BY (TRUNC(MONTHS_BETWEEN(SYSDATE,TO_DATE(SUBSTR(EMP_NO,1,6),'RRMMDD'))/12)+1) ASC
)
WHERE ROWNUM =1;
--
--4. 이름에 '성'자가 들어가는 직원들의 사번, 사원명, 부서명을 조회하시오.
SELECT EMP_ID, EMP_NAME, DEPT_NAME
FROM EMPLOYEE
JOIN DEPARTMENT USING(DEPT_ID)
WHERE EMP_NAME LIKE '%성%';
--
--5. 해외영업팀에 근무하는 사원명, 직급명, 부서코드, 부서명을 조회하시오.
SELECT EMP_NAME, JOB_TITLE, DEPT_ID, DEPT_NAME
FROM EMPLOYEE
JOIN JOB USING(JOB_ID)
JOIN DEPARTMENT USING(DEPT_ID)
WHERE DEPT_NAME LIKE '해외영업%';

--6. 보너스포인트를 받는 직원들의 사원명, 보너스포인트, 부서명, 근무지역명을 조회하시오.
SELECT EMP_NAME, BONUS_PCT, DEPT_NAME, LOC_DESCRIBE
FROM (
SELECT EMP_NAME, BONUS_PCT, DEPT_NAME, LOC_ID
FROM EMPLOYEE
JOIN DEPARTMENT USING (DEPT_ID)
WHERE BONUS_PCT > 0) E,
LOCATION L
WHERE E.LOC_ID = L.LOCATION_ID;

SELECT EMP_NAME, BONUS_PCT, DEPT_NAME, LOC_DESCRIBE
FROM EMPLOYEE
JOIN DEPARTMENT USING (DEPT_ID)
JOIN LOCATION ON (DEPARTMENT.LOC_ID = LOCATION.LOCATION_ID)
WHERE BONUS_PCT > 0;
--INNER JOIN ON 절 = 두 테이블의 컬럼명이 다를때
--USING 절 두테이블의 컬러럼명의 같을때

--
--
--7. 부서코드가 20인 직원들의 사원명, 직급명, 부서명, 근무지역명을 조회하시오.
SELECT EMP_NAME, JOB_TITLE, DEPT_NAME, LOC_DESCRIBE
FROM EMPLOYEE
JOIN JOB USING (JOB_ID)
JOIN DEPARTMENT USING(DEPT_ID)
JOIN LOCATION ON (DEPARTMENT.LOC_ID = LOCATION.LOCATION_ID)
WHERE DEPT_ID='20';
--
--
--8. 직급별 연봉의 최소급여(MIN_SAL)보다 많이 받는 직원들의
--사원명, 직급명, 급여, 연봉을 조회하시오.
--연봉에 보너스포인트를 적용하시오.
SELECT EMP_NAME 사원명, JOB_TITLE 직급명, SALARY 급여, ((SALARY+(SALARY*NVL(BONUS_PCT,0)))*12) 연봉
FROM EMPLOYEE
INNER JOIN JOB USING(JOB_ID)
WHERE ((SALARY+(SALARY*NVL(BONUS_PCT,0)))*12)>MIN_SAL;
--
--
--
--9. 한국(KO)과 일본(JP)에 근무하는 직원들의 
--사원명(emp_name), 부서명(dept_name), 지역명(loc_describe), 국가명(country_name)을 조회하시오.
SELECT EMP_NAME 사원명, DEPT_NAME 부서명, LOC_DESCRIBE 지역명, COUNTRY_NAME 국가명
FROM EMPLOYEE
INNER JOIN DEPARTMENT USING(DEPT_ID)
INNER JOIN LOCATION ON(DEPARTMENT.LOC_ID = LOCATION.LOCATION_ID)
INNER JOIN COUNTRY USING(COUNTRY_ID)
WHERE COUNTRY_ID IN ('KO','JP');
--
--10. 같은 부서에 근무하는 직원들의 사원명, 부서코드, 동료이름을 조회하시오.
--self join 사용
SELECT A.EMP_NAME 사원명, A.DEPT_ID 부서코드, B.EMP_NAME 동료이름
FROM EMPLOYEE A JOIN EMPLOYEE B
ON A.EMP_NAME <> B.EMP_NAME 
AND A.DEPT_ID = B.DEPT_ID
ORDER BY A.EMP_NAME;
--
--11. 보너스포인트가 없는 직원들 중에서 직급코드가 J4와 J7인 직원들의 사원명, 직급명, 급여를 조회하시오.
--단, join과 IN 사용할 것
SELECT EMP_NAME, JOB_TITLE, SALARY
FROM EMPLOYEE
INNER JOIN JOB USING(JOB_ID)
WHERE BONUS_PCT IS NULL  AND JOB_ID IN('J4','J7');
--
--
--12. 기혼인 직원과 미혼인 직원의 수를 조회하시오.
SELECT COUNT(DECODE(MARRIAGE,'Y','1',''))AS 기혼, COUNT(DECODE(MARRIAGE,'N','1',''))AS 미혼
FROM EMPLOYEE;

SELECT DECODE(MARRIAGE,'Y','기혼','N','미혼')AS 결혼유무, COUNT(*) 직원수
FROM EMPLOYEE
GROUP BY DECODE(MARRIAGE,'Y','기혼','N','미혼')
ORDER BY DECODE(MARRIAGE,'Y','기혼','N','미혼');